const fs = require('fs');
const path = require('path');
const https = require('https');

// Configuration
const SITE_URL = 'https://www.devstract.site';
const KEY_GENERATION_FILE = path.join(__dirname, '../public/indexnow-key.txt'); // We'll store the filename here for reference or just look in public

async function generateKey() {
  const key = require('crypto').randomBytes(16).toString('hex');
  const fileName = `${key}.txt`;
  const publicDir = path.join(__dirname, '../public');
  const outDir = path.join(__dirname, '../out');

  // Write to public/ for local dev and future builds
  fs.writeFileSync(path.join(publicDir, fileName), key);
  console.log(`File created at: public/${fileName}`);

  // Also write to out/ if it exists (for immediate deployment)
  if (fs.existsSync(outDir)) {
    fs.writeFileSync(path.join(outDir, fileName), key);
    console.log(`File created at: out/${fileName}`);
  }

  console.log(`Generated new IndexNow key: ${key}`);
  return key;
}

async function getUrlsFromSitemap(options = {}) {
  const { onlyRecent = false, daysThreshold = 7 } = options;

  // Check for sitemap.xml in out/ directory (generated by Next.js build)
  let sitemapPath = path.join(__dirname, '../out/sitemap.xml');

  if (!fs.existsSync(sitemapPath)) {
    // Fallback to public/ for development
    sitemapPath = path.join(__dirname, '../public/sitemap.xml');
  }

  if (!fs.existsSync(sitemapPath)) {
    console.error('Error: sitemap.xml not found. Run `pnpm build` first.');
    return { urls: [], stats: {} };
  }

  console.log(`Reading sitemap from: ${sitemapPath}`);
  const content = fs.readFileSync(sitemapPath, 'utf8');

  // Extract URL entries with their metadata
  const urlPattern = /<url>([\s\S]*?)<\/url>/g;
  const urlEntries = [...content.matchAll(urlPattern)];

  if (urlEntries.length === 0) {
    return { urls: [], stats: {} };
  }

  const now = new Date();
  const thresholdDate = new Date(now.getTime() - (daysThreshold * 24 * 60 * 60 * 1000));

  const allUrls = [];
  const recentUrls = [];
  const stats = {
    total: 0,
    recent: 0,
    older: 0,
    withoutDate: 0
  };

  for (const entry of urlEntries) {
    const urlBlock = entry[1];
    const locMatch = urlBlock.match(/<loc>(.*?)<\/loc>/);
    const lastModMatch = urlBlock.match(/<lastmod>(.*?)<\/lastmod>/);

    if (!locMatch) continue;

    const url = locMatch[1];
    allUrls.push(url);
    stats.total++;

    if (lastModMatch) {
      const lastModDate = new Date(lastModMatch[1]);

      if (lastModDate >= thresholdDate) {
        recentUrls.push(url);
        stats.recent++;
      } else {
        stats.older++;
      }
    } else {
      // No date found, consider it recent to be safe
      recentUrls.push(url);
      stats.withoutDate++;
    }
  }

  const urls = onlyRecent ? recentUrls : allUrls;

  return { urls, stats };
}

async function submitToIndexNow(key, urls) {
  if (urls.length === 0) {
    console.log('No URLs to submit.');
    return;
  }

  const data = JSON.stringify({
    host: 'www.devstract.site',
    key: key,
    keyLocation: `${SITE_URL}/${key}.txt`,
    urlList: urls
  });

  const options = {
    hostname: 'api.indexnow.org',
    port: 443,
    path: '/indexnow',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Content-Length': data.length
    }
  };

  return new Promise((resolve, reject) => {
    const req = https.request(options, (res) => {
      console.log(`IndexNow Status: ${res.statusCode}`);
      if (res.statusCode >= 200 && res.statusCode < 300) {
        console.log('Successfully submitted URLs to IndexNow.');
      }
      res.on('data', d => process.stdout.write(d));
      res.on('end', resolve);
    });

    req.on('error', (error) => {
      console.error('Error submitting to IndexNow:', error);
      reject(error);
    });

    req.write(data);
    req.end();
  });
}

async function main() {
  // 1. Check if key exists in public, else generate
  // For simplicity, let's look for a 32-char hex .txt file in public
  const publicDir = path.join(__dirname, '../public');
  const files = fs.readdirSync(publicDir);
  let keyFile = files.find(f => /^[a-f0-9]{32}\.txt$/.test(f));
  let key;

  if (keyFile) {
    key = keyFile.replace('.txt', '');
    console.log(`Found existing key: ${key}`);
  } else {
    console.log('No key found, generating new one...');
    key = await generateKey();
  }

  // 2. Determine submission strategy
  // Use INDEXNOW_MODE environment variable: 'all', 'recent', or default to 'all' for builds
  const mode = process.env.INDEXNOW_MODE || 'all';
  const daysThreshold = parseInt(process.env.INDEXNOW_DAYS || '7', 10);

  const onlyRecent = mode === 'recent';

  console.log(`\nIndexNow Mode: ${mode}`);
  if (onlyRecent) {
    console.log(`Submitting only URLs modified in the last ${daysThreshold} days\n`);
  } else {
    console.log('Submitting all URLs from sitemap\n');
  }

  // 3. Get URLs
  const { urls, stats } = await getUrlsFromSitemap({ onlyRecent, daysThreshold });

  // 4. Display stats
  console.log('Sitemap Analysis:');
  console.log(`  Total URLs: ${stats.total}`);
  console.log(`  Recent URLs (≤${daysThreshold} days): ${stats.recent}`);
  console.log(`  Older URLs: ${stats.older}`);
  if (stats.withoutDate > 0) {
    console.log(`  URLs without date: ${stats.withoutDate}`);
  }
  console.log(`\nSubmitting ${urls.length} URLs to IndexNow...\n`);

  // 5. Submit
  await submitToIndexNow(key, urls);
}

main().catch(console.error);
